import * as vscode from 'vscode';

// -----------------------------------------------------------------------
// Language configurations
// -----------------------------------------------------------------------

interface CommentConfig {
  lineComment?: string[];
  blockComment?: Array<[string, string]>;
  /** Sorted longest-first so triple quotes are matched before single quotes */
  stringDelimiters?: string[];
}

const LANGUAGE_CONFIG: Record<string, CommentConfig> = {
  javascript:       { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['`', '"', "'"] },
  typescript:       { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['`', '"', "'"] },
  javascriptreact:  { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['`', '"', "'"] },
  typescriptreact:  { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['`', '"', "'"] },
  python:           { lineComment: ['#'], stringDelimiters: ['"""', "'''", '"', "'"] },
  ruby:             { lineComment: ['#'], stringDelimiters: ['"', "'"] },
  shellscript:      { lineComment: ['#'], stringDelimiters: ['"', "'"] },
  html:             { blockComment: [['<!--', '-->']] },
  css:              { blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  scss:             { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  less:             { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  c:                { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  cpp:              { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  java:             { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  go:               { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['`', '"'] },
  rust:             { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['"'] },
  php:              { lineComment: ['//', '#'], blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  swift:            { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['"'] },
  kotlin:           { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['`', '"', "'"] },
  csharp:           { lineComment: ['//'], blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  lua:              { lineComment: ['--'], blockComment: [['--[[', ']]']], stringDelimiters: ['"', "'"] },
  sql:              { lineComment: ['--'], blockComment: [['/*', '*/']], stringDelimiters: ['"', "'"] },
  yaml:             { lineComment: ['#'], stringDelimiters: ['"', "'"] },
  toml:             { lineComment: ['#'], stringDelimiters: ['"""', "'''", '"', "'"] },
  ini:              { lineComment: ['#', ';'], stringDelimiters: ['"', "'"] },
  makefile:         { lineComment: ['#'] },
  dockerfile:       { lineComment: ['#'] },
  r:                { lineComment: ['#'], stringDelimiters: ['"', "'"] },
  perl:             { lineComment: ['#'], stringDelimiters: ['"', "'"] },
  coffeescript:     { lineComment: ['#'], blockComment: [['###', '###']], stringDelimiters: ['"', "'", '`'] },
};

// -----------------------------------------------------------------------
// 42 header detection
// -----------------------------------------------------------------------

/**
 * Detects the 42 school standard file header.
 *
 * Every 42 header contains the distinctive ASCII art `:::      ::::::::`
 * generated by the Norme header tool — unique enough to be a reliable
 * fingerprint without false-positives in real source files.
 *
 * Example:
 *   /* ************************************************************************** *\/
 *   /*                                                        :::      ::::::::   *\/
 *   /* filename.c                                           :+:      :+:    :+:  *\/
 *   /* ************************************************************************** *\/
 */
export function is42Header(blockCommentText: string): boolean {
  return blockCommentText.includes(':::      ::::::::');
}

// -----------------------------------------------------------------------
// Options
// -----------------------------------------------------------------------

export interface RemoveOptions {
  /** When true, 42 school file headers are kept intact. Default: true */
  preserve42Header?: boolean;
}

// -----------------------------------------------------------------------
// State-machine comment remover
// -----------------------------------------------------------------------

/**
 * Removes comments from `text` while:
 *  - Correctly ignoring comment-like sequences inside string literals.
 *  - Optionally preserving 42 school file headers.
 *
 * Block comments are fully buffered before being discarded so that
 * preserve predicates can inspect the entire comment at once.
 * Line counts are maintained: a discarded block comment is replaced by
 * the same number of newlines it contained, preventing line-number drift.
 */
export function removeComments(
  text: string,
  config: CommentConfig,
  options: RemoveOptions = {},
): string {
  const { preserve42Header = true } = options;

  const lineComments  = config.lineComment  ?? [];
  const blockComments = config.blockComment ?? [];
  const stringDelims  = [...(config.stringDelimiters ?? [])].sort((a, b) => b.length - a.length);

  let result             = '';
  let i                  = 0;
  let inString           = false;
  let stringChar         = '';
  let inLineComment      = false;
  let inBlockComment     = false;
  let blockCommentEnd    = '';
  let blockCommentBuffer = '';   // accumulates the full block comment

  while (i < text.length) {
    const ch = text[i];

    // ── Newline ────────────────────────────────────────────────────────
    if (ch === '\n') {
      if (inBlockComment) {
        blockCommentBuffer += '\n';  // buffer, decide later
        i++;
        continue;
      }
      inLineComment = false;         // line comment ends at EOL
      result += '\n';
      i++;
      continue;
    }

    // ── Inside a line comment ──────────────────────────────────────────
    if (inLineComment) {
      i++;
      continue;
    }

    // ── Inside a block comment ─────────────────────────────────────────
    if (inBlockComment) {
      if (text.startsWith(blockCommentEnd, i)) {
        blockCommentBuffer += blockCommentEnd;
        i                  += blockCommentEnd.length;
        inBlockComment      = false;

        if (preserve42Header && is42Header(blockCommentBuffer)) {
          // Keep the 42 header exactly as written
          result += blockCommentBuffer;
        } else {
          // Discard the comment, but emit one '\n' per buffered newline
          // so that subsequent line numbers are not affected
          const newlines = (blockCommentBuffer.match(/\n/g) ?? []).length;
          result += '\n'.repeat(newlines);
        }

        blockCommentBuffer = '';
      } else {
        blockCommentBuffer += ch;
        i++;
      }
      continue;
    }

    // ── Inside a string literal ────────────────────────────────────────
    if (inString) {
      if (ch === '\\') {
        result += ch + (text[i + 1] ?? '');
        i += 2;
        continue;
      }
      if (text.startsWith(stringChar, i)) {
        result += stringChar;
        i      += stringChar.length;
        inString = false;
        continue;
      }
      result += ch;
      i++;
      continue;
    }

    // ── Normal mode: probe for string / block comment / line comment ───

    // String start (longest delimiter wins)
    let matched = false;
    for (const delim of stringDelims) {
      if (text.startsWith(delim, i)) {
        inString   = true;
        stringChar = delim;
        result    += delim;
        i         += delim.length;
        matched    = true;
        break;
      }
    }
    if (matched) { continue; }

    // Block comment start — begin buffering (include opening delimiter)
    for (const [start, end] of blockComments) {
      if (text.startsWith(start, i)) {
        inBlockComment     = true;
        blockCommentEnd    = end;
        blockCommentBuffer = start;
        i                 += start.length;
        matched            = true;
        break;
      }
    }
    if (matched) { continue; }

    // Line comment start
    for (const lc of lineComments) {
      if (text.startsWith(lc, i)) {
        inLineComment = true;
        i            += lc.length;
        matched       = true;
        break;
      }
    }
    if (matched) { continue; }

    // Ordinary character
    result += ch;
    i++;
  }

  return result;
}

// -----------------------------------------------------------------------
// Post-processing helpers
// -----------------------------------------------------------------------

/**
 * After comment removal:
 *  1. Trims trailing whitespace on every line.
 *  2. Collapses 2+ consecutive blank lines into a single blank line.
 *  3. Strips leading / trailing blank lines.
 */
export function cleanupText(text: string): string {
  const lines = text.split('\n').map(l => l.trimEnd());

  const out: string[] = [];
  let blankRun = 0;

  for (const line of lines) {
    if (line.trim() === '') {
      blankRun++;
      if (blankRun <= 1) { out.push(line); }
    } else {
      blankRun = 0;
      out.push(line);
    }
  }

  while (out.length > 0 && out[0].trim() === '')              { out.shift(); }
  while (out.length > 0 && out[out.length - 1].trim() === '') { out.pop(); }

  return out.join('\n') + '\n';
}

// -----------------------------------------------------------------------
// Extension entry points
// -----------------------------------------------------------------------

export function activate(context: vscode.ExtensionContext): void {
  const disposable = vscode.commands.registerCommand(
    'delete-comments.deleteComments',
    async () => {
      const editor = vscode.window.activeTextEditor;
      if (!editor) {
        vscode.window.showWarningMessage('delete-comments: No active editor.');
        return;
      }

      const { document } = editor;
      const languageId   = document.languageId;
      const config       = LANGUAGE_CONFIG[languageId];

      if (!config) {
        vscode.window.showWarningMessage(
          `delete-comments: "${languageId}" is not supported yet.`
        );
        return;
      }

      // Read user settings
      const settings = vscode.workspace.getConfiguration('delete-comments');
      const options: RemoveOptions = {
        preserve42Header: settings.get<boolean>('preserve42Header', true),
      };

      const original = document.getText();
      const result   = cleanupText(removeComments(original, config, options));

      if (result === original) {
        vscode.window.showInformationMessage('delete-comments: No comments found.');
        return;
      }

      await editor.edit(builder => {
        const fullRange = new vscode.Range(
          document.positionAt(0),
          document.positionAt(original.length)
        );
        builder.replace(fullRange, result);
      });

      vscode.window.showInformationMessage('delete-comments: Comments removed ✓');
    }
  );

  context.subscriptions.push(disposable);
}

export function deactivate(): void { /* nothing to clean up */ }